FIXUP: BACKPORT: FROMLIST: mm: multigenerational lru: aging
0-day reports:

mm/vmscan.c:3226:26: error:
	macro "pte_index" requires 2 arguments, but only 1 given

BUG=b:123039911
TEST=Built

Disallow-Recycled-Builds: test-failures
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Yu Zhao <yuzhao@google.com>
Change-Id: If650fb0440702571fce9bbfc8ff708010e9f6707
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2998151
Tested-by: Yu Zhao <yuzhao@chromium.org>
Auto-Submit: Yu Zhao <yuzhao@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Yu Zhao <yuzhao@chromium.org>
Commit-Queue: Yu Zhao <yuzhao@chromium.org>
Signed-off-by: Cyber Knight <cyberknight755@gmail.com>
Signed-off-by: Abhishek001konni <Abhishek001konni@gmail.com>